### ISSUE TITLE
I/flutter ( 6690): MediaQuery.of() called with a context that does not contain a MediaQuery.

### ISSUE THREAD

**Issue by emailsubjekt** [FilledStacks/smart_flare#12]
This is your regular github https://github.com/FilledStacks/smart_flare - the example that you name in the readme file. I'm using pubspec 

-------------------------------
  smart_flare: ^0.2.8
-------------------------------

main.dart

import 'package:flutter/material.dart';
import 'package:smart_flare/smart_flare.dart';

void main() => runApp(FlareDemo());

class FlareDemo extends StatefulWidget {
  @override
  _FlareDemoState createState() => _FlareDemoState();
}

class _FlareDemoState extends State<FlareDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        body: SmartFlareActor(
            width: 295.0,
            height: 251.0,
            filename: 'animations/rotating_star.flr'));
  }
}

Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
I/flutter ( 6690): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6690): The following assertion was thrown building FlareDemo(state: _FlareDemoState#11c6e):
I/flutter ( 6690): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 6690): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 6690): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 6690): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 6690): The context used was:
I/flutter ( 6690):   Scaffold(dirty, state: ScaffoldState#a0c0f(lifecycle state: initialized, tickers: tracking 2
I/flutter ( 6690): tickers))
I/flutter ( 6690): 
I/flutter ( 6690): When the exception was thrown, this was the stack:
I/flutter ( 6690): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:696:5)
I/flutter ( 6690): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1842:50)
I/flutter ( 6690): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
I/flutter ( 6690): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6690): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6690): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6690): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6690): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6690): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 6690): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 6690): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6690): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6690): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6690): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 6690): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 6690): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 6690): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6690): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 6690): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 6690): #19     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 6690): #20     main (package:boring_star_test/main.dart:5:16)
I/flutter ( 6690): #21     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter ( 6690): #26     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter ( 6690): #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 6690): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 6690): (elided 4 frames from package dart:async)
I/flutter ( 6690): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6690): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6690): The following assertion was thrown building FlareDemo(state: _FlareDemoState#4cf98):
I/flutter ( 6690): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 6690): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 6690): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 6690): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 6690): The context used was:
I/flutter ( 6690):   Scaffold(dirty, state: ScaffoldState#9c424(lifecycle state: initialized, tickers: tracking 2
I/flutter ( 6690): tickers))
I/flutter ( 6690): 
I/flutter ( 6690): When the exception was thrown, this was the stack:
I/flutter ( 6690): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:696:5)
I/flutter ( 6690): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1842:50)
I/flutter ( 6690): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
I/flutter ( 6690): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6690): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6690): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6690): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6690): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6690): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 6690): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 6690): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6690): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6690): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6690): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 6690): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 6690): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 6690): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6690): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 6690): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 6690): #19     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 6690): #20     main (package:boring_star_test/main.dart:5:16)
I/flutter ( 6690): #21     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter ( 6690): #26     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter ( 6690): #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 6690): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 6690): (elided 4 frames from package dart:async)
I/flutter ( 6690): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6908): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6908): The following assertion was thrown building FlareDemo(state: _FlareDemoState#1370a):
I/flutter ( 6908): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 6908): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 6908): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 6908): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 6908): The context used was:
I/flutter ( 6908):   Scaffold(dirty, state: ScaffoldState#86916(lifecycle state: initialized, tickers: tracking 2
I/flutter ( 6908): tickers))
I/flutter ( 6908): 
I/flutter ( 6908): When the exception was thrown, this was the stack:
I/flutter ( 6908): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:696:5)
I/flutter ( 6908): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1842:50)
I/flutter ( 6908): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
I/flutter ( 6908): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6908): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6908): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6908): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6908): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6908): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 6908): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 6908): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6908): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6908): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6908): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 6908): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 6908): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 6908): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6908): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 6908): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 6908): #19     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 6908): #20     main (package:boring_star_test/main.dart:5:16)
I/flutter ( 6908): #21     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter ( 6908): #26     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter ( 6908): #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 6908): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 6908): (elided 4 frames from package dart:async)
I/flutter ( 6908): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6908): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6908): The following assertion was thrown building FlareDemo(state: _FlareDemoState#5c7fa):
I/flutter ( 6908): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 6908): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 6908): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 6908): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 6908): The context used was:
I/flutter ( 6908):   Scaffold(dirty, state: ScaffoldState#ab8d9(lifecycle state: initialized, tickers: tracking 2
I/flutter ( 6908): tickers))
I/flutter ( 6908): 
I/flutter ( 6908): When the exception was thrown, this was the stack:
I/flutter ( 6908): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:696:5)
I/flutter ( 6908): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1842:50)
I/flutter ( 6908): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4051:12)
I/flutter ( 6908): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6908): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6908): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6908): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6908): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6908): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 6908): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 6908): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 6908): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 6908): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 6908): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter ( 6908): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter ( 6908): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter ( 6908): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6908): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter ( 6908): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 6908): #19     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter ( 6908): #20     main (package:boring_star_test/main.dart:5:16)
I/flutter ( 6908): #21     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter ( 6908): #26     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter ( 6908): #27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
I/flutter ( 6908): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 6908): (elided 4 frames from package dart:async)
I/flutter ( 6908): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6908): Width of the screen: 411.42857142857144
I/flutter ( 6908): Width of the screen: 411.42857142857144
I/flutter ( 7045): Width of the screen: 411.42857142857144
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...
I/flutter (13743): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13743): The following assertion was thrown building FlareDemo(state: _FlareDemoState#95d47):
I/flutter (13743): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (13743): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (13743): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (13743): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (13743): The context used was:
I/flutter (13743):   Scaffold
I/flutter (13743): 
I/flutter (13743): The relevant error-causing widget was:
I/flutter (13743):   FlareDemo file:///D:/FlutterDell/Test152-Flare2/BoringStarTest/boring_star_test/lib/main.dart:4:23
I/flutter (13743): 
I/flutter (13743): When the exception was thrown, this was the stack:
I/flutter (13743): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:798:5)
I/flutter (13743): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1993:50)
I/flutter (13743): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
I/flutter (13743): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (13743): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (13743): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (13743): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (13743): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (13743): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (13743): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter (13743): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (13743): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (13743): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (13743): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (13743): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (13743): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (13743): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (13743): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (13743): #18     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (13743): #19     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (13743): #28     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (13743): #29     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (13743): #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (13743): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (13743): 
I/flutter (13743): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by FilledStacks** [comment]
It'll first need to be upgraded to AndroidX then check what's happening there. will probably be able to look at it in 3-4 weeks. taking a 2 week break now then I'll  be back. Fix it up, make a PR and then I'll review it and accept if it's fine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
